#! /bin/bash 
./bin/main ./config/P2_config.json & 
./bin/main ./config/P3_config.json & 
./bin/main ./config/P4_config.json & 
./bin/main ./config/P5_config.json & 
./bin/main ./config/P6_config.json & 
./bin/main ./config/P7_config.json & 
./bin/main ./config/P8_config.json & 
./bin/main ./config/P9_config.json & 
./bin/main ./config/P10_config.json & 
./bin/main ./config/P11_config.json & 
./bin/main ./config/P12_config.json & 
./bin/main ./config/P13_config.json & 
./bin/main ./config/P14_config.json & 
./bin/main ./config/P15_config.json & 
./bin/main ./config/P16_config.json & 
./bin/main ./config/P17_config.json & 
./bin/main ./config/P18_config.json & 
./bin/main ./config/P19_config.json & 
./bin/main ./config/P20_config.json & 
./bin/main ./config/P21_config.json & 
./bin/main ./config/P22_config.json & 
./bin/main ./config/P23_config.json & 
./bin/main ./config/P24_config.json & 
./bin/main ./config/P25_config.json & 
./bin/main ./config/P26_config.json & 
./bin/main ./config/P27_config.json & 
./bin/main ./config/P28_config.json & 
./bin/main ./config/P29_config.json & 
./bin/main ./config/P30_config.json & 
./bin/main ./config/P31_config.json & 
./bin/main ./config/P32_config.json & 
./bin/main ./config/P33_config.json & 
./bin/main ./config/P34_config.json & 
./bin/main ./config/P35_config.json & 
./bin/main ./config/P36_config.json & 
./bin/main ./config/P37_config.json & 
./bin/main ./config/P38_config.json & 
./bin/main ./config/P39_config.json & 
./bin/main ./config/P40_config.json & 
./bin/main ./config/P41_config.json & 
./bin/main ./config/P42_config.json & 
./bin/main ./config/P43_config.json & 
./bin/main ./config/P44_config.json & 
./bin/main ./config/P45_config.json & 
./bin/main ./config/P46_config.json & 
./bin/main ./config/P47_config.json & 
./bin/main ./config/P48_config.json & 
./bin/main ./config/P49_config.json & 
./bin/main ./config/P50_config.json & 
./bin/main ./config/P51_config.json & 
./bin/main ./config/P52_config.json & 
./bin/main ./config/P53_config.json & 
./bin/main ./config/P54_config.json & 
./bin/main ./config/P55_config.json & 
./bin/main ./config/P56_config.json & 
./bin/main ./config/P57_config.json & 
./bin/main ./config/P58_config.json & 
./bin/main ./config/P59_config.json & 
./bin/main ./config/P60_config.json & 
./bin/main ./config/P61_config.json & 
./bin/main ./config/P62_config.json & 
./bin/main ./config/P63_config.json & 
./bin/main ./config/P64_config.json & 
./bin/main ./config/P65_config.json & 
./bin/main ./config/P66_config.json & 
./bin/main ./config/P67_config.json & 
./bin/main ./config/P68_config.json & 
./bin/main ./config/P69_config.json & 
./bin/main ./config/P70_config.json & 
./bin/main ./config/P71_config.json & 
./bin/main ./config/P72_config.json & 
./bin/main ./config/P73_config.json & 
./bin/main ./config/P74_config.json & 
./bin/main ./config/P75_config.json & 
./bin/main ./config/P76_config.json & 
./bin/main ./config/P77_config.json & 
./bin/main ./config/P78_config.json & 
./bin/main ./config/P79_config.json & 
./bin/main ./config/P80_config.json & 
./bin/main ./config/P81_config.json & 
./bin/main ./config/P82_config.json & 
./bin/main ./config/P83_config.json & 
./bin/main ./config/P84_config.json & 
./bin/main ./config/P85_config.json & 
./bin/main ./config/P86_config.json & 
./bin/main ./config/P87_config.json & 
./bin/main ./config/P88_config.json & 
./bin/main ./config/P89_config.json & 
./bin/main ./config/P90_config.json & 
./bin/main ./config/P91_config.json & 
./bin/main ./config/P92_config.json & 
./bin/main ./config/P93_config.json & 
./bin/main ./config/P94_config.json & 
./bin/main ./config/P95_config.json & 
./bin/main ./config/P96_config.json & 
./bin/main ./config/P97_config.json & 
./bin/main ./config/P98_config.json & 
./bin/main ./config/P99_config.json & 
./bin/main ./config/P100_config.json & 
./bin/main ./config/P1_config.json