#! /bin/bash 
./bin/main ./config/P2_config.json & 
./bin/main ./config/P3_config.json & 
./bin/main ./config/P4_config.json & 
./bin/main ./config/P5_config.json & 
./bin/main ./config/P6_config.json & 
./bin/main ./config/P7_config.json & 
./bin/main ./config/P8_config.json & 
./bin/main ./config/P9_config.json & 
./bin/main ./config/P10_config.json & 
./bin/main ./config/P11_config.json & 
./bin/main ./config/P12_config.json & 
./bin/main ./config/P13_config.json & 
./bin/main ./config/P14_config.json & 
./bin/main ./config/P15_config.json & 
./bin/main ./config/P16_config.json & 
./bin/main ./config/P17_config.json & 
./bin/main ./config/P18_config.json & 
./bin/main ./config/P19_config.json & 
./bin/main ./config/P20_config.json & 
./bin/main ./config/P21_config.json & 
./bin/main ./config/P22_config.json & 
./bin/main ./config/P23_config.json & 
./bin/main ./config/P24_config.json & 
./bin/main ./config/P25_config.json & 
./bin/main ./config/P26_config.json & 
./bin/main ./config/P27_config.json & 
./bin/main ./config/P28_config.json & 
./bin/main ./config/P29_config.json & 
./bin/main ./config/P30_config.json & 
./bin/main ./config/P31_config.json & 
./bin/main ./config/P32_config.json & 
./bin/main ./config/P33_config.json & 
./bin/main ./config/P34_config.json & 
./bin/main ./config/P35_config.json & 
./bin/main ./config/P36_config.json & 
./bin/main ./config/P37_config.json & 
./bin/main ./config/P38_config.json & 
./bin/main ./config/P39_config.json & 
./bin/main ./config/P40_config.json & 
./bin/main ./config/P41_config.json & 
./bin/main ./config/P42_config.json & 
./bin/main ./config/P43_config.json & 
./bin/main ./config/P44_config.json & 
./bin/main ./config/P45_config.json & 
./bin/main ./config/P46_config.json & 
./bin/main ./config/P47_config.json & 
./bin/main ./config/P48_config.json & 
./bin/main ./config/P49_config.json & 
./bin/main ./config/P50_config.json & 
./bin/main ./config/P1_config.json